name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: anjalitalan
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FFA8CB&color_dots=#F7EDE4,#51C9B340,#51C9B380,#51C9B3BF,#51C9B3
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FFA8CB&color_dots=#161B22,#51C9B340,#51C9B380,#51C9B3BF,#51C9B3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish contribution snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
